<?php
/**
 * FileName: I18N.php.
 * Author: liupeng
 * Date: 2015/8/20
 */

namespace modules\components\i18n;

/**
 * 语言国际化
 * Class I18N
 * @package modules\components\i18n
 */
class I18N extends \yii\i18n\I18N {
    public $suffix = 'frontend';
    /**
     * @inheritDoc
     */
    public function init() {
        parent::init(); // TODO: Change the autogenerated stub
        if (!isset($this->translations['common/'.$this->suffix]) && !isset($this->translations['*'])) {
            $this->translations['common/'.$this->suffix] = [
                'class' => 'yii\i18n\PhpMessageSource',
                'basePath' => '@modules/views/'.$this->suffix.'/messages',
                'fileMap'=>
                    ['common/'.$this->suffix=>'common.php']
            ];
        }
    }


}