<?php
/**
 * FileName: BackendController.php.
 * Author: liupeng
 * Date: 2015/8/15
 */

namespace modules\components\controllers;

use modules\components\assets\BackendAssetBundle;
use yii\helpers\ArrayHelper;

class BackendController extends \liuxy\admin\components\Controller {
    /**
     * @inheritDoc
     */
    public function afterAction($action, $result) {
        /**
         * 注册页面js函数
         */

        if (!$this->request->getIsAjax()) {
            if ($this->module) {
                $currentModuleId = $this->module->getUniqueId();
                BackendAssetBundle::registerJsFile($this->getView(), $currentModuleId);
            }
        }
        return parent::afterAction($action, $result);
    }

    /**
     * 获取查询参数
     * @param $opt
     */
    protected function loadOperation(&$opt) {
        $params = ArrayHelper::merge ( $this->request->post (), $this->request->get () );
        foreach ( $params as $key => $value ) {
            if (! in_array ( $key, [
                    'modsubmit',
                    'submit',
                    'formhash',
                    'page'
                ] ) && $value != null && $value != '') {
                $opt[$key] = $value;
            }
        }
    }




    /**
     * @inheritDoc
     */
    /*public function getViewPath() {
        $viewPath = parent::getViewPath(); // TODO: Change the autogenerated stub
        if (strpos($viewPath, "/index")) {
            $viewPath = str_replace("/index", "", $viewPath);
        }
        return $viewPath;
    }*/


}